CREATE DATABASE IF NOT EXISTS chat_app; USE chat_app; 
CREATE TABLE users
 (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50), email VARCHAR(100), 
 password VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP); 
 CREATE TABLE chat_rooms 
 (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP); 
 CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, room_id INT DEFAULT 1, user_id INT, message_text TEXT, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);